/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ListSubjectsImport } from './routes/list-subjects'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ListSubjectsRoute = ListSubjectsImport.update({
  path: '/list-subjects',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/list-subjects': {
      id: '/list-subjects'
      path: '/list-subjects'
      fullPath: '/list-subjects'
      preLoaderRoute: typeof ListSubjectsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/list-subjects': typeof ListSubjectsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/list-subjects': typeof ListSubjectsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/list-subjects': typeof ListSubjectsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/list-subjects'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/list-subjects'
  id: '__root__' | '/' | '/list-subjects'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ListSubjectsRoute: typeof ListSubjectsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ListSubjectsRoute: ListSubjectsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/list-subjects"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/list-subjects": {
      "filePath": "list-subjects.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
