/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TeachersListingImport } from './routes/teachers-listing'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TeachersListingRoute = TeachersListingImport.update({
  path: '/teachers-listing',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/teachers-listing': {
      id: '/teachers-listing'
      path: '/teachers-listing'
      fullPath: '/teachers-listing'
      preLoaderRoute: typeof TeachersListingImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/teachers-listing': typeof TeachersListingRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/teachers-listing': typeof TeachersListingRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/teachers-listing': typeof TeachersListingRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/teachers-listing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/teachers-listing'
  id: '__root__' | '/' | '/teachers-listing'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TeachersListingRoute: typeof TeachersListingRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TeachersListingRoute: TeachersListingRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/teachers-listing"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/teachers-listing": {
      "filePath": "teachers-listing.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
